# Generated by Django 6.1 on 2026-08-27 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('logo', models.FileField(upload_to='uploads/portfolio/companies_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=4192, verbose_name='Description')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.jobexperience')),
            ],
        ),
    ]
