# Generated by Django 6.1 on 2026-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='position',
            field=models.CharField(default='CHANGEME', verbose_name='Position'),
            preserve_default=False,
        ),
    ]
