# Generated by Django 6.1.1 on 2026-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_alter_jobtask_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color',
            field=models.CharField(default='000000', max_length=6, verbose_name='Color (hex)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to='portfolio/companies_logo/'),
        ),
    ]
