# Generated by Django 6.1.1 on 2026-10-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projecttag_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(max_length=512, verbose_name='Short description'),
        ),
    ]
