# Generated by Django 6.1.1 on 2026-10-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttag',
            name='dark_text',
            field=models.BooleanField(default=False, verbose_name='Dark text'),
        ),
    ]
